### ISSUE TITLE
Some links on the UMT guides page don't work

### ISSUE THREAD

**Issue by xmerta00** [Kentico/xperience-by-kentico-universal-migration-tool#39]
Hi, the first three links on this page: https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/tree/main/docs#convert--import-samples throw the 404 Page not found errors:

1. https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/blob/main/docs/docs/README.md
2. https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/blob/main/docs/examples/Kentico.Xperience.UMT.Example.Console/README.md
3. https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/blob/main/docs/examples/Kentico.Xperience.UMT.Example.AdminApp/README.md

Can you please update them? Thank you.

**Comment by seangwright** [comment]
These should probably be updated to reference a git tag so that all links of this type could be updated with a find/replace with the commit that bumps the version.

Example: [https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/tree/v1.3.0/docs/Model/ChannelModel.md](https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/tree/v1.3.0/docs/Model/ChannelModel.md)

**Comment by xmerta00** [comment]
The first link on the page in question still doesn't work:
Advanced usage is covered in the [extended documentation](https://github.com/Kentico/xperience-by-kentico-universal-migration-tool/blob/main/docs/docs/README.md).
